# 70g should be enough for FLCCA no filtered genotype data
cd ./Adventitial_fibroblasts ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=Adventitial_fibroblasts_TWAS ; cd ..
cd ./Alveolar_fibroblasts ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=Alveolar_fibroblasts_TWAS ; cd ..
cd ./Alveolar_macrophages ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=Alveolar_macrophages_TWAS ; cd ..
cd ./Alveolar_macrophages_CCL3 ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=Alveolar_macrophages_CCL3_TWAS ; cd ..
cd ./Alveolar_macrophages_MT ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=Alveolar_macrophages_MT_TWAS ; cd ..
cd ./Alveolar_transitional_cells ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=Alveolar_transitional_cells_TWAS ; cd ..
cd ./AT1 ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=AT1_TWAS ; cd ..
cd ./AT2 ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=AT2_TWAS ; cd ..
cd ./B_cells ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=B_cells_TWAS ; cd ..
cd ./Basal ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=Basal_TWAS ; cd ..
cd ./CD4_T_cells ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=CD4_T_cells_TWAS ; cd ..
cd ./CD8_T_cells ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=CD8_T_cells_TWAS ; cd ..
cd ./Classical_monocyte ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=Classical_monocyte_TWAS ; cd ..
cd ./Club ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=Club_TWAS ; cd ..
cd ./DC2 ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=DC2_TWAS ; cd ..
cd ./EC_aerocyte_capillary ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=EC_aerocyte_capillary_TWAS ; cd ..
cd ./EC_arterial ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=EC_arterial_TWAS ; cd ..
cd ./EC_general_capillary ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=EC_general_capillary_TWAS ; cd ..
cd ./EC_venous_pulmonary ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=EC_venous_pulmonary_TWAS ; cd ..
cd ./EC_venous_systemic ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=EC_venous_systemic_TWAS ; cd ..
cd ./Goblet ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=Goblet_TWAS ; cd ..
cd ./Interstitial_macrophages ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=Interstitial_macrophages_TWAS ; cd ..
cd ./Lymphatic_EC ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=Lymphatic_EC_TWAS ; cd ..
cd ./Mast_cells ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=Mast_cells_TWAS ; cd ..
cd ./Mesothelium ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=Mesothelium_TWAS ; cd ..
cd ./Multiciliated ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=Multiciliated_TWAS ; cd ..
cd ./NK_cells ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=NK_cells_TWAS ; cd ..
cd ./NK_T_cells ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=NK_T_cells_TWAS ; cd ..
cd ./Non_classical_monocytes ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=Non_classical_monocytes_TWAS ; cd ..
cd ./Plasmacytoid_DCs ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=Plasmacytoid_DCs_TWAS ; cd ..
cd ./Secretory_transitional_cells ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=Secretory_transitional_cells_TWAS ; cd ..
cd ./SMC ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=SMC_TWAS ; cd ..
cd ./T_cell_proliferating ; mkdir old_rst_wo_covs ; mv *.rstbyisoform.* old_rst_wo_covs/ ; sbatch --mem=100g --time=48:00:00 run_TWAS_byisoform.sh --job-name=T_cell_proliferating_TWAS ; cd ..
