# 70g should be enough for FLCCA no filtered genotype data
cd ./Adventitial_fibroblasts ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=Adventitial_fibroblasts_TWAS ; cd ..
cd ./Alveolar_fibroblasts ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=Alveolar_fibroblasts_TWAS ; cd ..
cd ./Alveolar_macrophages ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=Alveolar_macrophages_TWAS ; cd ..
cd ./Alveolar_macrophages_CCL3 ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=Alveolar_macrophages_CCL3_TWAS ; cd ..
cd ./Alveolar_macrophages_MT ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=Alveolar_macrophages_MT_TWAS ; cd ..
cd ./Alveolar_transitional_cells ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=Alveolar_transitional_cells_TWAS ; cd ..
cd ./AT1 ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=AT1_TWAS ; cd ..
cd ./AT2 ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=AT2_TWAS ; cd ..
cd ./B_cells ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=B_cells_TWAS ; cd ..
cd ./Basal ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=Basal_TWAS ; cd ..
cd ./CD4_T_cells ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=CD4_T_cells_TWAS ; cd ..
cd ./CD8_T_cells ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=CD8_T_cells_TWAS ; cd ..
cd ./Classical_monocyte ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=Classical_monocyte_TWAS ; cd ..
cd ./Club ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=Club_TWAS ; cd ..
cd ./DC2 ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=DC2_TWAS ; cd ..
cd ./EC_aerocyte_capillary ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=EC_aerocyte_capillary_TWAS ; cd ..
cd ./EC_arterial ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=EC_arterial_TWAS ; cd ..
cd ./EC_general_capillary ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=EC_general_capillary_TWAS ; cd ..
cd ./EC_venous_pulmonary ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=EC_venous_pulmonary_TWAS ; cd ..
cd ./EC_venous_systemic ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=EC_venous_systemic_TWAS ; cd ..
cd ./Goblet ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=Goblet_TWAS ; cd ..
cd ./Interstitial_macrophages ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=Interstitial_macrophages_TWAS ; cd ..
cd ./Lymphatic_EC ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=Lymphatic_EC_TWAS ; cd ..
cd ./Mast_cells ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=Mast_cells_TWAS ; cd ..
cd ./Mesothelium ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=Mesothelium_TWAS ; cd ..
cd ./Multiciliated ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=Multiciliated_TWAS ; cd ..
cd ./NK_cells ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=NK_cells_TWAS ; cd ..
cd ./NK_T_cells ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=NK_T_cells_TWAS ; cd ..
cd ./Non_classical_monocytes ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=Non_classical_monocytes_TWAS ; cd ..
cd ./Plasmacytoid_DCs ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=Plasmacytoid_DCs_TWAS ; cd ..
cd ./Secretory_transitional_cells ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=Secretory_transitional_cells_TWAS ; cd ..
cd ./SMC ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=SMC_TWAS ; cd ..
cd ./T_cell_proliferating ; sbatch --mem=200g --time=24:00:00 run_TWAS.sh --job-name=T_cell_proliferating_TWAS ; cd ..
